#---------------------------
# GitHub Action for C labs 
# Daniel Bondarcov, 2021
#---------------------------
name: ClabsActions

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compiling and testing lab 1
      working-directory: ./first_lab
      run: make Makefile all
    - name: compiling and testing lab 2.1
      working-directory: ./second_lab/task1
      run: make Makefile all
