#---------------------------
# GitHub Action for C labs 
# Daniel Bondarcov, 2021
#---------------------------
name: ClabsActions

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: compiling and testing lab
      run: |
       for %d in (sub-*) do (
       cd %d
       make
       cd ..
       )
