#---------------------------
# GitHub Action for C labs 
# Daniel Bondarcov, 2021
#---------------------------
name: ClabsActions

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Print Message
       run: echo "it works"
        
