#---------------------------
# GitHub Action for C labs 
# Daniel Bondarcov, 2021
#---------------------------
name: ClabsActions

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compiling and testing
      run: |
        for d in */ ; do
        cd "$d"
        make all
        cd ..
        done
