#---------------------------
# GitHub Action for C labs 
# Daniel Bondarcov, 2021
#---------------------------
name: ClabsActions

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build first lab:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile and test
      working-directory: ./first_lab
      run: make Makefile all
  build second lab:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile and test
      working-directory: ./second_lab
      run: make Makefile all      
      
