name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          cd ./seventh_lab
          gcc -ftest-coverage -fprofile-arcs -O0 -o test test.c ClintList.c
          ./test
          gcov -abcfu ClintList.c
      - name: Upload
        uses: codecov/codecov-action@v1
        with: |
          cd ./seventh_lab
          files: ./ClintList.c.gcov
