name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
        include:
         - os: ubuntu-latest
           compiler: gcc
           version: 6.3.0
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          cd ./seventh_lab
          gcc -ftest-coverage -fprofile-arcs -O0 -o test test.c ClintList.c
          ./test
          gcov -abcfu ClintList.c
      - name: Upload
        uses: codecov/codecov-action@v1
        with: 
          files: ./seventh_lab/ClintList.c.gcov
