name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Upload
        uses: codecov/codecov-action@v1
        with: 
          files: |
            ./seventh_lab/code-coverage/ClintList.c.gcov
            ./seventh_lab/code-coverage/GoodsList.c.gcov
